# Generated by Django 6.1 on 2026-08-24 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("city", models.CharField(max_length=120, verbose_name="city")),
                ("country", models.CharField(max_length=120, verbose_name="country")),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("consulting", "Consulting"),
                            ("mission", "Short mission"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="contract type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Mission, responsibilities, team context.",
                        verbose_name="description",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="requirements"),
                ),
                (
                    "compensation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. “Competitive”, a range, or leave empty.",
                        max_length=200,
                        verbose_name="compensation",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Optional: applications stay open when empty.",
                        null=True,
                        verbose_name="application deadline",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["company", "donor"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="published by",
                    ),
                ),
            ],
            options={
                "verbose_name": "job",
                "verbose_name_plural": "jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(
                        help_text="Why you fit this mission: certified experience speaks first.",
                        verbose_name="cover letter",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Not retained"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="applied at"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decided at"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        limit_choices_to={"role": "expert"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="applicant",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "job application",
                "verbose_name_plural": "job applications",
                "ordering": ["-applied_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "applicant"), name="unique_application_per_job"
                    )
                ],
            },
        ),
    ]
