# Generated by Django 6.1 on 2026-09-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="published_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="published by",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applicant",
            field=models.ForeignKey(
                limit_choices_to={"role": "user"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="applicant",
            ),
        ),
    ]
