# Generated by Django 6.1 on 2026-09-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_published_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "mission",
                "verbose_name_plural": "missions",
            },
        ),
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-applied_at"],
                "verbose_name": "candidature",
                "verbose_name_plural": "candidatures",
            },
        ),
        migrations.AlterField(
            model_name="job",
            name="city",
            field=models.CharField(max_length=120, verbose_name="ville"),
        ),
        migrations.AlterField(
            model_name="job",
            name="compensation",
            field=models.CharField(
                blank=True,
                help_text="ex. « Compétitive », une fourchette, ou laissez vide.",
                max_length=200,
                verbose_name="rémunération",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Temps plein"),
                    ("part_time", "Temps partiel"),
                    ("consulting", "Consultance"),
                    ("mission", "Mission courte"),
                ],
                default="full_time",
                max_length=20,
                verbose_name="type de contrat",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="country",
            field=models.CharField(max_length=120, verbose_name="pays"),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
        ),
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateField(
                blank=True,
                help_text="Facultatif : les candidatures restent ouvertes si vide.",
                null=True,
                verbose_name="date limite de candidature",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(
                help_text="Mission, responsabilités, contexte de l'équipe.",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="published_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="publiée par",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="requirements",
            field=models.TextField(blank=True, verbose_name="prérequis"),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("open", "Ouverte"), ("closed", "Clôturée")],
                db_index=True,
                default="open",
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=200, verbose_name="titre"),
        ),
        migrations.AlterField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="mise à jour le"),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applicant",
            field=models.ForeignKey(
                limit_choices_to={"role": "user"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="candidat",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="candidature déposée le"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cover_letter",
            field=models.TextField(
                help_text="En quoi vous correspondez à cette mission : l'expérience certifiée parle en premier.",
                verbose_name="lettre de motivation",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="decided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="décidée le"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En cours d'examen"),
                    ("accepted", "Acceptée"),
                    ("rejected", "Non retenue"),
                ],
                default="pending",
                max_length=20,
                verbose_name="statut",
            ),
        ),
    ]
