# Generated by Django 6.1 on 2026-08-22 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "official_name",
                    models.CharField(max_length=255, verbose_name="official name"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "deliverables",
                    models.TextField(
                        help_text="One deliverable per line.",
                        verbose_name="deliverables",
                    ),
                ),
                ("duration_start", models.DateField(verbose_name="duration start")),
                (
                    "duration_end",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty for an ongoing project.",
                        null=True,
                        verbose_name="duration end",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        verbose_name="budget",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=255, verbose_name="client name"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=20,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "company"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="published by",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ["-duration_start", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration_end__gte", models.F("duration_start"))
                        ),
                        name="project_duration_end_after_start",
                    )
                ],
            },
        ),
    ]
