# Generated by Django 6.1 on 2026-08-24 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="label")),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "project link",
                "verbose_name_plural": "project links",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                        verbose_name="kind",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Used for images and documents.",
                        upload_to="project_media/%Y/%m/",
                        verbose_name="file",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Used for embedded videos (YouTube).",
                        max_length=500,
                        verbose_name="video URL",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="caption"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
                ),
            ],
            options={
                "verbose_name": "project media",
                "verbose_name_plural": "project media",
                "ordering": ["id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="project",
            name="project_duration_end_after_start",
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration_end__gte", models.F("duration_start")),
                    ("duration_end__isnull", True),
                    _connector="OR",
                ),
                name="project_duration_end_after_start",
            ),
        ),
        migrations.AddField(
            model_name="projectlink",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmedia",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_items",
                to="projects.project",
            ),
        ),
    ]
