# Generated by Django 6.1 on 2026-09-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_published_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmedia",
            name="url",
        ),
        migrations.AlterField(
            model_name="projectmedia",
            name="kind",
            field=models.CharField(
                choices=[("image", "Image"), ("document", "Document")],
                max_length=20,
                verbose_name="kind",
            ),
        ),
    ]
