# Generated by Django 6.1 on 2026-09-20 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_projectmedia_url_alter_projectmedia_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "iso3",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        null=True,
                        unique=True,
                        verbose_name="ISO 3166-1 alpha-3",
                    ),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Funder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=160, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "funder",
                "verbose_name_plural": "funders",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "project tag",
                "verbose_name_plural": "project tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="intervention_volume",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The volume of intervention, in the unit chosen below.",
                null=True,
                verbose_name="intervention volume",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="personal_end",
            field=models.DateField(
                blank=True,
                help_text="Leave empty if your participation is ongoing.",
                null=True,
                verbose_name="personal participation end",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="personal_start",
            field=models.DateField(
                blank=True,
                help_text="Start of YOUR personal participation (subset of the project duration).",
                null=True,
                verbose_name="personal participation start",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase",
            field=models.CharField(
                choices=[("ongoing", "Ongoing"), ("completed", "Completed")],
                default="ongoing",
                help_text="Business status: ongoing or completed.",
                max_length=20,
                verbose_name="phase",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="volume_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person_days", "person-days"),
                    ("person_months", "person-months"),
                ],
                max_length=20,
                null=True,
                verbose_name="volume unit",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured country of intervention; type a name and it is reused.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.country",
                verbose_name="country",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="funder",
            field=models.ForeignKey(
                blank=True,
                help_text="Funder (bailleur), distinct from the maître d'ouvrage: who finances the project rather than who commissioned it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.funder",
                verbose_name="funder",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Comma-separated thematic keywords; reused across projects.",
                related_name="projects",
                to="projects.projecttag",
                verbose_name="thematic keywords",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("personal_end__gte", models.F("personal_start")),
                    ("personal_end__isnull", True),
                    ("personal_start__isnull", True),
                    _connector="OR",
                ),
                name="project_personal_end_after_start",
            ),
        ),
    ]
