# Generated by Django 6.1 on 2026-09-20 14:15

import django.db.models.deletion
from django.db import migrations, models


def backfill_clients(apps, schema_editor):
    Client = apps.get_model("projects", "Client")
    Project = apps.get_model("projects", "Project")
    seen = {}
    for project in Project.objects.exclude(client_name="").order_by("id"):
        raw_name = (project.client_name or "").strip()
        if not raw_name:
            continue
        key = raw_name.casefold()
        client = seen.get(key)
        if client is None:
            client = Client.objects.filter(name__iexact=raw_name).first()
            if client is None:
                client = Client.objects.create(name=raw_name)
            seen[key] = client
        project.client_id = client.pk
        project.client_name = client.name
        project.save(update_fields=["client", "client_name"])


def clear_client_links(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.update(client=None)


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_country_funder_projecttag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=160, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured client / maître d'ouvrage; reused for coherent search and filters.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.client",
                verbose_name="client",
            ),
        ),
        migrations.RunPython(backfill_clients, clear_client_links),
    ]
