# Generated by Django 6.1 on 2026-09-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_client_referential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["name"],
                "verbose_name": "pays",
                "verbose_name_plural": "pays",
            },
        ),
        migrations.AlterModelOptions(
            name="funder",
            options={
                "ordering": ["name"],
                "verbose_name": "bailleur",
                "verbose_name_plural": "bailleurs",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-duration_start", "-id"],
                "verbose_name": "projet",
                "verbose_name_plural": "projets",
            },
        ),
        migrations.AlterModelOptions(
            name="projectlink",
            options={
                "ordering": ["id"],
                "verbose_name": "lien de projet",
                "verbose_name_plural": "liens de projet",
            },
        ),
        migrations.AlterModelOptions(
            name="projectmedia",
            options={
                "ordering": ["id"],
                "verbose_name": "média de projet",
                "verbose_name_plural": "médias de projet",
            },
        ),
        migrations.AlterModelOptions(
            name="projecttag",
            options={
                "ordering": ["name"],
                "verbose_name": "mot-clé de projet",
                "verbose_name_plural": "mots-clés de projet",
            },
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=160, unique=True, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="funder",
            name="name",
            field=models.CharField(max_length=160, unique=True, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client / maître d'ouvrage structuré ; réutilisé pour une recherche et des filtres cohérents.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.client",
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client_name",
            field=models.CharField(max_length=255, verbose_name="nom du client"),
        ),
        migrations.AlterField(
            model_name="project",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Pays d'intervention structuré ; saisissez un nom et il est réutilisé.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.country",
                verbose_name="pays",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
        ),
        migrations.AlterField(
            model_name="project",
            name="deliverables",
            field=models.TextField(
                help_text="Un livrable par ligne.", verbose_name="livrables"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="duration_end",
            field=models.DateField(
                blank=True,
                help_text="Laissez vide pour un projet en cours.",
                null=True,
                verbose_name="date de fin",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="duration_start",
            field=models.DateField(verbose_name="date de début"),
        ),
        migrations.AlterField(
            model_name="project",
            name="funder",
            field=models.ForeignKey(
                blank=True,
                help_text="Bailleur, distinct du maître d'ouvrage : qui finance le projet plutôt que qui l'a commandé.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.funder",
                verbose_name="bailleur",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="intervention_volume",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Le volume d'intervention, dans l'unité choisie ci-dessous.",
                null=True,
                verbose_name="volume d'intervention",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="official_name",
            field=models.CharField(max_length=255, verbose_name="nom officiel"),
        ),
        migrations.AlterField(
            model_name="project",
            name="personal_end",
            field=models.DateField(
                blank=True,
                help_text="Laissez vide si votre participation est toujours en cours.",
                null=True,
                verbose_name="fin de la participation personnelle",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="personal_start",
            field=models.DateField(
                blank=True,
                help_text="Début de VOTRE participation personnelle (sous-ensemble de la durée du projet).",
                null=True,
                verbose_name="début de la participation personnelle",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="phase",
            field=models.CharField(
                choices=[("ongoing", "En cours"), ("completed", "Terminé")],
                default="ongoing",
                help_text="Statut du projet : en cours ou achevé.",
                max_length=20,
                verbose_name="phase",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="published_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="publié par",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("published", "Publié"),
                    ("archived", "Archivé"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Mots-clés thématiques séparés par des virgules ; réutilisés sur plusieurs projets.",
                related_name="projects",
                to="projects.projecttag",
                verbose_name="mots-clés thématiques",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="modifié le"),
        ),
        migrations.AlterField(
            model_name="project",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Privé")],
                default="private",
                max_length=20,
                verbose_name="visibilité",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="volume_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("person_days", "jours-personnes"),
                    ("person_months", "mois-personnes"),
                ],
                max_length=20,
                null=True,
                verbose_name="unité de volume",
            ),
        ),
        migrations.AlterField(
            model_name="projectlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
        ),
        migrations.AlterField(
            model_name="projectlink",
            name="label",
            field=models.CharField(max_length=120, verbose_name="libellé"),
        ),
        migrations.AlterField(
            model_name="projectmedia",
            name="caption",
            field=models.CharField(blank=True, max_length=200, verbose_name="légende"),
        ),
        migrations.AlterField(
            model_name="projectmedia",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Utilisé pour les images et les documents.",
                upload_to="project_media/%Y/%m/",
                verbose_name="fichier",
            ),
        ),
        migrations.AlterField(
            model_name="projectmedia",
            name="kind",
            field=models.CharField(
                choices=[("image", "Image"), ("document", "Document")],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="projectmedia",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ajouté le"),
        ),
        migrations.AlterField(
            model_name="projecttag",
            name="name",
            field=models.CharField(max_length=60, unique=True, verbose_name="nom"),
        ),
    ]
