# Generated by Django 6.1 on 2026-08-22 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invited_email",
                    models.EmailField(
                        help_text="Email used to reach the expert; mirrors the linked account email when the expert already exists (deduplication rule 5).",
                        max_length=254,
                        verbose_name="invited email",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("director", "Director"),
                            ("manager", "Manager"),
                            ("assistant", "Assistant"),
                            ("specialist", "Specialist"),
                        ],
                        max_length=20,
                        verbose_name="role type",
                    ),
                ),
                (
                    "contribution_bullets",
                    models.TextField(
                        help_text="One bullet per line describing what the expert actually delivered.",
                        verbose_name="contribution bullets",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("pending_confirmation", "Pending confirmation"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="invited",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmed at"
                    ),
                ),
                (
                    "pending_company_validation",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
                (
                    "dispute_reason",
                    models.TextField(blank=True, verbose_name="dispute reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            ("role", "company"), ("is_superuser", True), _connector="OR"
                        ),
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declared_contributions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="added by",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(
                            ("role", "expert"), ("is_superuser", True), _connector="OR"
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="expert",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="projects.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project contribution",
                "verbose_name_plural": "project contributions",
                "ordering": ["project_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExpertInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="sent at"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("opened", "Opened"),
                            ("converted", "Converted"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="sent",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "reminder_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="reminder count"
                    ),
                ),
                (
                    "contribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="certification.projectcontribution",
                        verbose_name="contribution",
                    ),
                ),
            ],
            options={
                "verbose_name": "expert invitation",
                "verbose_name_plural": "expert invitations",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectcontribution",
            constraint=models.UniqueConstraint(
                fields=("project", "invited_email", "role_type"),
                name="uniq_contribution_project_email_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcontribution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "confirmed"), _negated=True),
                    ("confirmed_at__isnull", False),
                    _connector="OR",
                ),
                name="confirmed_contribution_has_confirmed_at",
            ),
        ),
    ]
