# Generated by Django 6.1 on 2026-09-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcontribution",
            name="added_by",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("email_confirmed", True)),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="declared_contributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="added by",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="expert",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("email_confirmed", True)),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="expert",
            ),
        ),
    ]
