# Generated by Django 6.1 on 2026-09-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0002_alter_projectcontribution_added_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcontribution",
            name="client_confirm_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Secret one-time token emailed to the client / maître d'ouvrage to confirm a contribution without needing an account (T1).",
                null=True,
                unique=True,
                verbose_name="client confirmation token",
            ),
        ),
        migrations.AddField(
            model_name="projectcontribution",
            name="confirmation_source",
            field=models.CharField(
                choices=[
                    ("expert", "Named expert"),
                    ("client", "Client / maître d'ouvrage"),
                    ("lead_firm", "Groupement lead firm"),
                ],
                default="expert",
                help_text="Who must counter-sign this contribution: the named expert, the client / maître d'ouvrage, or the groupement lead firm.",
                max_length=20,
                verbose_name="confirmation source",
            ),
        ),
        migrations.AddField(
            model_name="projectcontribution",
            name="confirmed_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("expert", "Named expert"),
                    ("client", "Client / maître d'ouvrage"),
                    ("lead_firm", "Groupement lead firm"),
                ],
                help_text="Which counter-signing actor actually validated the contribution.",
                max_length=20,
                verbose_name="confirmed by",
            ),
        ),
    ]
