# Generated by Django 6.1 on 2026-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0003_projectcontribution_client_confirm_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcontribution",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("director", "Director"),
                    ("manager", "Manager"),
                    ("assistant", "Assistant"),
                    ("specialist", "Specialist"),
                    ("consultant", "Consultant"),
                    ("engineer", "Engineer"),
                    ("other", "Other"),
                ],
                max_length=20,
                verbose_name="role type",
            ),
        ),
    ]
