# Generated by Django 6.1 on 2026-09-21 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certification", "0004_widen_role_type_choices"),
        ("projects", "0007_alter_country_options_alter_funder_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expertinvitation",
            options={
                "ordering": ["-sent_at"],
                "verbose_name": "invitation d'expert",
                "verbose_name_plural": "invitations d'expert",
            },
        ),
        migrations.AlterModelOptions(
            name="projectcontribution",
            options={
                "ordering": ["project_id", "id"],
                "verbose_name": "contribution de projet",
                "verbose_name_plural": "contributions de projet",
            },
        ),
        migrations.AlterField(
            model_name="expertinvitation",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expire le"),
        ),
        migrations.AlterField(
            model_name="expertinvitation",
            name="reminder_count",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="nombre de relances"
            ),
        ),
        migrations.AlterField(
            model_name="expertinvitation",
            name="sent_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="envoyé le"),
        ),
        migrations.AlterField(
            model_name="expertinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Envoyée"),
                    ("opened", "Ouverte"),
                    ("converted", "Convertie"),
                    ("expired", "Expirée"),
                ],
                db_index=True,
                default="sent",
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="expertinvitation",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="jeton"
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="added_by",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("email_confirmed", True)),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="declared_contributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ajouté par",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="client_confirm_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Jeton secret à usage unique envoyé par email au client / maître d'ouvrage pour confirmer une contribution sans nécessiter de compte (T1).",
                null=True,
                unique=True,
                verbose_name="jeton de confirmation client",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="confirmation_source",
            field=models.CharField(
                choices=[
                    ("expert", "Expert nommé"),
                    ("client", "Client / maître d'ouvrage"),
                    ("lead_firm", "Groupement / entreprise mandataire"),
                ],
                default="expert",
                help_text="Qui doit contre-signer cette contribution : l'expert nommé, le client / maître d'ouvrage, ou le groupement / entreprise mandataire.",
                max_length=20,
                verbose_name="source de confirmation",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="confirmé le"
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="confirmed_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("expert", "Expert nommé"),
                    ("client", "Client / maître d'ouvrage"),
                    ("lead_firm", "Groupement / entreprise mandataire"),
                ],
                help_text="Quel acteur contre-signataire a réellement validé la contribution.",
                max_length=20,
                verbose_name="confirmé par",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="contribution_bullets",
            field=models.TextField(
                help_text="Une réalisation par ligne décrivant ce que l'expert a réellement livré.",
                verbose_name="Réalisations",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="dispute_reason",
            field=models.TextField(blank=True, verbose_name="motif de contestation"),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="invited_email",
            field=models.EmailField(
                help_text="Email utilisé pour joindre l'expert ; reflète l'email du compte lié lorsque l'expert existe déjà (règle de déduplication 5).",
                max_length=254,
                verbose_name="Email de l'invité",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="projects.project",
                verbose_name="projet",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="motif de refus"),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("director", "Directeur"),
                    ("manager", "Responsable"),
                    ("assistant", "Assistant"),
                    ("specialist", "Spécialiste"),
                    ("consultant", "Consultant"),
                    ("engineer", "Ingénieur"),
                    ("other", "Autre"),
                ],
                max_length=20,
                verbose_name="type de rôle",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invité"),
                    ("pending_confirmation", "En attente de confirmation"),
                    ("confirmed", "Confirmé"),
                    ("rejected", "Refusé"),
                    ("disputed", "Contesté"),
                ],
                db_index=True,
                default="invited",
                max_length=30,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
        ),
    ]
