# Generated by Django 6.1 on 2026-08-22 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpertProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="headline"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="bio")),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="city"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="ISO country name; supports pan-African then international scaling.",
                        max_length=120,
                        verbose_name="country",
                    ),
                ),
                (
                    "cv_template",
                    models.CharField(
                        choices=[
                            ("academic_harvard_mit", "Academic (Harvard/MIT)"),
                            ("afd", "AFD"),
                            ("world_bank", "World Bank"),
                        ],
                        default="academic_harvard_mit",
                        help_text="Reserved for the CV generator (Epic 7).",
                        max_length=40,
                        verbose_name="CV template",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="experts",
                        to="accounts.skill",
                        verbose_name="skills",
                    ),
                ),
            ],
            options={
                "verbose_name": "expert profile",
                "verbose_name_plural": "expert profiles",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "institution",
                    models.CharField(max_length=255, verbose_name="institution"),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="accounts.expertprofile",
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "training",
                "verbose_name_plural": "trainings",
                "ordering": ["-year", "title"],
            },
        ),
    ]
