# Generated by Django 6.1 on 2026-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_skill_expertprofile_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Shared across all roles; used on dashboards and public profiles.",
                upload_to="avatars/",
                verbose_name="profile picture",
            ),
        ),
    ]
