# Generated by Django 6.1 on 2026-09-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="organisation_name",
        ),
        migrations.AddField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(
                blank=True,
                help_text="Six-digit code used to confirm the email address.",
                max_length=10,
                verbose_name="confirmation code",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="confirmation_code_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Used to expire the code 24h after it was issued.",
                null=True,
                verbose_name="confirmation code created at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False, verbose_name="email confirmed"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Used on dashboards and public profiles.",
                upload_to="avatars/",
                verbose_name="profile picture",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                db_index=True,
                default="user",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.company",
                verbose_name="company",
            ),
        ),
    ]
