# Generated by Django 6.1 on 2026-09-20 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_companymembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Optional; kept private and never shown on the public site.",
                null=True,
                verbose_name="date of birth",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="countries_of_intervention",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Derivable from certified projects; also editable by hand.",
                verbose_name="countries of intervention",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='One entry per language with three distinct levels, e.g. {"name": "French", "read": "fluent", "write": "fluent", "speak": "native"}',
                verbose_name="languages",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="misc",
            field=models.TextField(
                blank=True,
                help_text="Short free-form block: membership numbers, certifications…",
                verbose_name="miscellaneous",
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="nationality"
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="phone"),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="strengths",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="3–5 short items displayed at the top of the generated CV.",
                verbose_name="key strengths",
            ),
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="association / body"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="role held"
                    ),
                ),
                (
                    "year_start",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="start year"
                    ),
                ),
                (
                    "year_end",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="end year"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="accounts.expertprofile",
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "mandate",
                "verbose_name_plural": "mandates",
                "ordering": ["-year_start", "name"],
            },
        ),
        migrations.CreateModel(
            name="MediaAppearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "outlet",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="outlet / support"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=500, verbose_name="URL"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_appearances",
                        to="accounts.expertprofile",
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "media appearance",
                "verbose_name_plural": "media appearances",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer", models.CharField(max_length=255, verbose_name="employer")),
                ("function", models.CharField(max_length=255, verbose_name="function")),
                ("date_start", models.DateField(verbose_name="start")),
                (
                    "date_end",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty for a current position.",
                        null=True,
                        verbose_name="end",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="accounts.expertprofile",
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "position",
                "verbose_name_plural": "positions",
                "ordering": ["-date_start"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "venue",
                    models.CharField(
                        blank=True,
                        help_text="Journal, report series, conference, web…",
                        max_length=255,
                        verbose_name="outlet / support",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="accounts.expertprofile",
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "publication",
                "verbose_name_plural": "publications",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="TeachingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="course / activity"),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="institution"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="year"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_entries",
                        to="accounts.expertprofile",
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "teaching activity",
                "verbose_name_plural": "teaching activities",
                "ordering": ["-year", "title"],
            },
        ),
    ]
