# Generated by Django 6.1 on 2026-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_expertprofile_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="accreditations",
            field=models.JSONField(
                blank=True, default=list, verbose_name="accreditations"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=120, verbose_name="country"),
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="company",
            name="domains",
            field=models.JSONField(blank=True, default=list, verbose_name="domains"),
        ),
        migrations.AddField(
            model_name="company",
            name="founded_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="founded year"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="size",
            field=models.CharField(blank=True, max_length=120, verbose_name="size"),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, verbose_name="website"),
        ),
    ]
