# Generated by Django 6.1 on 2026-09-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_company_accreditations_company_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "structure",
                "verbose_name_plural": "structures",
            },
        ),
        migrations.AlterModelOptions(
            name="companymembership",
            options={
                "ordering": ["-requested_at"],
                "verbose_name": "affiliation à une structure",
                "verbose_name_plural": "affiliations à une structure",
            },
        ),
        migrations.AlterModelOptions(
            name="expertprofile",
            options={
                "verbose_name": "profil d'expert",
                "verbose_name_plural": "profils d'expert",
            },
        ),
        migrations.AlterModelOptions(
            name="mandate",
            options={
                "ordering": ["-year_start", "name"],
                "verbose_name": "mandat",
                "verbose_name_plural": "mandats",
            },
        ),
        migrations.AlterModelOptions(
            name="mediaappearance",
            options={
                "ordering": ["-year", "title"],
                "verbose_name": "apparition médiatique",
                "verbose_name_plural": "apparitions médiatiques",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["-date_start"],
                "verbose_name": "poste",
                "verbose_name_plural": "postes",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["name"],
                "verbose_name": "compétence",
                "verbose_name_plural": "compétences",
            },
        ),
        migrations.AlterModelOptions(
            name="teachingentry",
            options={
                "ordering": ["-year", "title"],
                "verbose_name": "activité d'enseignement",
                "verbose_name_plural": "activités d'enseignement",
            },
        ),
        migrations.AlterModelOptions(
            name="training",
            options={
                "ordering": ["-year", "title"],
                "verbose_name": "formation",
                "verbose_name_plural": "formations",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="accreditations",
            field=models.JSONField(
                blank=True, default=list, verbose_name="accréditations"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=120, verbose_name="pays"),
        ),
        migrations.AlterField(
            model_name="company",
            name="domains",
            field=models.JSONField(blank=True, default=list, verbose_name="domaines"),
        ),
        migrations.AlterField(
            model_name="company",
            name="founded_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="année de création"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="company",
            name="size",
            field=models.CharField(blank=True, max_length=120, verbose_name="taille"),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, verbose_name="site web"),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="accounts.company",
                verbose_name="structure",
            ),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="requested_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="demandé le"),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="demandé par",
            ),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="examiné le"
            ),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="examiné par",
            ),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrateur"), ("member", "Membre")],
                default="member",
                max_length=20,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Demandée"),
                    ("invited", "Invitée"),
                    ("approved", "Approuvée"),
                    ("declined", "Refusée"),
                ],
                db_index=True,
                default="requested",
                max_length=20,
                verbose_name="statut",
            ),
        ),
        migrations.AlterField(
            model_name="companymembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="biographie"),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Facultatif ; conservé confidentiel et jamais affiché sur le site public.",
                null=True,
                verbose_name="date de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="ville"),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="countries_of_intervention",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Dérivables des projets certifiés ; également modifiables à la main.",
                verbose_name="pays d'intervention",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Nom du pays au format ISO ; permet un déploiement panafricain puis international.",
                max_length=120,
                verbose_name="pays",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="cv_template",
            field=models.CharField(
                choices=[
                    ("academic_harvard_mit", "Académique (Harvard/MIT)"),
                    ("afd", "AFD"),
                    ("world_bank", "Banque mondiale"),
                ],
                default="academic_harvard_mit",
                help_text="Réservé au générateur de CV.",
                max_length=40,
                verbose_name="modèle de CV",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="headline",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="titre / accroche"
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Une entrée par langue avec trois niveaux distincts, ex. {"name": "French", "read": "fluent", "write": "fluent", "speak": "native"}',
                verbose_name="langues",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="misc",
            field=models.TextField(
                blank=True,
                help_text="Bloc libre court : numéros d'affiliation, certifications…",
                verbose_name="divers",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="nationalité"
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="téléphone"),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="experts",
                to="accounts.skill",
                verbose_name="compétences",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="strengths",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="3 à 5 éléments courts affichés en haut du CV généré.",
                verbose_name="points forts",
            ),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
        ),
        migrations.AlterField(
            model_name="expertprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expert_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="mandate",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="association / organisme"
            ),
        ),
        migrations.AlterField(
            model_name="mandate",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandates",
                to="accounts.expertprofile",
                verbose_name="profil",
            ),
        ),
        migrations.AlterField(
            model_name="mandate",
            name="role",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="rôle occupé"
            ),
        ),
        migrations.AlterField(
            model_name="mandate",
            name="year_end",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="année de fin"
            ),
        ),
        migrations.AlterField(
            model_name="mandate",
            name="year_start",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="année de début"
            ),
        ),
        migrations.AlterField(
            model_name="mediaappearance",
            name="outlet",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="média / support"
            ),
        ),
        migrations.AlterField(
            model_name="mediaappearance",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_appearances",
                to="accounts.expertprofile",
                verbose_name="profil",
            ),
        ),
        migrations.AlterField(
            model_name="mediaappearance",
            name="title",
            field=models.CharField(max_length=255, verbose_name="titre"),
        ),
        migrations.AlterField(
            model_name="mediaappearance",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="année"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="date_end",
            field=models.DateField(
                blank=True,
                help_text="Laissez vide pour un poste actuel.",
                null=True,
                verbose_name="fin",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="date_start",
            field=models.DateField(verbose_name="début"),
        ),
        migrations.AlterField(
            model_name="position",
            name="employer",
            field=models.CharField(max_length=255, verbose_name="employeur"),
        ),
        migrations.AlterField(
            model_name="position",
            name="function",
            field=models.CharField(max_length=255, verbose_name="fonction"),
        ),
        migrations.AlterField(
            model_name="position",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="accounts.expertprofile",
                verbose_name="profil",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="accounts.expertprofile",
                verbose_name="profil",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=255, verbose_name="titre"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="venue",
            field=models.CharField(
                blank=True,
                help_text="Revue, série de rapports, conférence, web…",
                max_length=255,
                verbose_name="support / revue",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="année"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="teachingentry",
            name="institution",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="établissement"
            ),
        ),
        migrations.AlterField(
            model_name="teachingentry",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_entries",
                to="accounts.expertprofile",
                verbose_name="profil",
            ),
        ),
        migrations.AlterField(
            model_name="teachingentry",
            name="title",
            field=models.CharField(max_length=255, verbose_name="cours / activité"),
        ),
        migrations.AlterField(
            model_name="teachingentry",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="année"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="institution",
            field=models.CharField(max_length=255, verbose_name="établissement"),
        ),
        migrations.AlterField(
            model_name="training",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainings",
                to="accounts.expertprofile",
                verbose_name="profil",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="title",
            field=models.CharField(max_length=255, verbose_name="titre"),
        ),
        migrations.AlterField(
            model_name="training",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="année"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Utilisée sur les tableaux de bord et les profils publics.",
                upload_to="avatars/",
                verbose_name="photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.company",
                verbose_name="structure",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="confirmation_code",
            field=models.CharField(
                blank=True,
                help_text="Code à six chiffres utilisé pour confirmer l'adresse email.",
                max_length=10,
                verbose_name="code de confirmation",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="confirmation_code_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Utilisé pour faire expirer le code 24 heures après son émission.",
                null=True,
                verbose_name="code de confirmation créé le",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="adresse email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False, verbose_name="email confirmé"),
        ),
        migrations.AlterField(
            model_name="user",
            name="professional_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Identifiant professionnel unique, gratuit et permanent (OX-XXXXXX). Attribué à la création, jamais modifié.",
                max_length=16,
                unique=True,
                verbose_name="identifiant professionnel",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "Utilisateur"), ("admin", "Administrateur")],
                db_index=True,
                default="user",
                max_length=20,
                verbose_name="rôle",
            ),
        ),
    ]
