# Generated by Django 6.1 on 2026-09-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_company_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de la confirmation de l'adresse email. Vide tant qu'aucun email n'a jamais été confirmé : distingue une première inscription d'un changement d'email en attente.",
                null=True,
                verbose_name="email confirmé le",
            ),
        ),
    ]
