# Generated by Django 6.1 on 2026-09-23 02:30

from django.db import migrations


def forward(apps, schema_editor):
    ExpertProfile = apps.get_model("accounts", "ExpertProfile")
    ExpertProfile.objects.filter(cv_template="world_bank").update(
        cv_template="world_bank_new"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_user_email_confirmed_at"),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]