# Generated by Django 6.1 on 2026-09-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_world_bank_new_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertprofile",
            name="cv_template",
            field=models.CharField(
                choices=[
                    ("academic_harvard_mit", "Académique (Harvard/MIT)"),
                    ("afd", "AFD"),
                    ("world_bank_new", "Banque mondiale"),
                ],
                default="academic_harvard_mit",
                help_text="Réservé au générateur de CV.",
                max_length=40,
                verbose_name="modèle de CV",
            ),
        ),
    ]
