# Generated by Django 6.1 on 2026-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_expertprofile_cv_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertprofile",
            name="cv_template",
            field=models.CharField(
                choices=[("afd", "AFD"), ("world_bank_new", "Banque mondiale")],
                default="world_bank_new",
                help_text="Réservé au générateur de CV.",
                max_length=40,
                verbose_name="modèle de CV",
            ),
        ),
    ]
